server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/zelda?useUnicode=true&allowMultiQueries=true&autoReconnect=true&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 1000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 1
      validation-query: select 1
      validation-query-timeout: 30
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      filter:
        log4j2:
          statement-executable-sql-log-enable: true
      web-stat-filter:
        profile-enable: true
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: root
        login-password: root
        reset-enable: true

mybatis:
  mapper-locations: classpath*:/mapping/**/*.xml
  type-aliases-package: com.zelda.entity
  configuration:
    map-underscore-to-camel-case: false
    default-fetch-size: 50
    default-statement-timeout: 10
    auto-mapping-unknown-column-behavior: warning
    use-actual-param-name: false

logging:
  level:
    root: info